### ISSUE TITLE
Save file format

### ISSUE THREAD

**Issue by kreuzberger** [pdrb/dbj#1]
Hi!
My main purpose for the project would be to store and share the database in human readable format in git.
To solve conflicts if 2 users change the entries, it would be helpful to have the indent specified to store each doc on an extra line?
Seems loading of the json files with newlines manually added seem to be no problem.
Would this be an valid improvement?

**Comment by pdrb** [comment]
Hi Jörg!

I will update the code to include an option to save a prettified json.

**Comment by pdrb** [comment]
Just released a new version with an indent option to save:

save(indent=None) -> Save database to disk.
Args:
    indent (int or str, optional): If provided, save a prettified json with that indent level. 0, negative or "" will only insert newlines.

Hope this helps :)
