### ISSUE TITLE
when using combined query with and,only latter condition queryed

### ISSUE THREAD

**Issue by forgetmenot6413** [pdrb/dbj#2]
when I used followling
xxx=db.find(  'aaa > 10' and 'bbb >= 6660' )
only bbb >= 6660'  takes effect
thanks

**Comment by pdrb** [comment]
It's because the entire query must be a string, like:

`db.find('aaa > 10 and bbb >= 6660')`

Pay attention to the single quotes above. I did a simple test and it worked as expected:

```
>>> db.insert({'aaa': 11, 'bbb': 6660})
'a4eedd30730811eba760029c898f64a8'
>>> db.insert({'aaa': 10, 'bbb': 6660})
'ac36f8ac730811eba760029c898f64a8'
>>> db.find('aaa > 10 and bbb >= 6660')
['a4eedd30730811eba760029c898f64a8']
```

Hope this helps :)
